name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./Actividad1/devops-practice/

      - name: Run tests
        run: npm test
        working-directory: ./Actividad1/devops-practice/
      
      # Paso 5: Inicia sesión en DockerHub (requiere credenciales)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 6: Construye la imagen Docker
      - name: Build Docker image
        run: docker build -t devops-practice .

      # Paso 7: Etiqueta la imagen Docker
      - name: Tag Docker image
        run: docker tag devops-practice:latest your-dockerhub-username/devops-practice:latest

      # Paso 8: Publica la imagen en DockerHub
      - name: Push Docker image to DockerHub
        run: docker push your-dockerhub-username/devops-practice:latest

      # Paso 9: Corre el contenedor Docker (opcional)
      - name: Run Docker container
        run: docker run -d -p 3000:3000 your-dockerhub-username/devops-practice:latest
